set(SOURCE_FILES
  src/bt_runner.cpp
  src/utils/load_waypoints.cpp
  bt_nodes/AdvanceIndex.cpp
  bt_nodes/CheckIfSetupDone.cpp
  bt_nodes/InitialSetup.cpp
  bt_nodes/IsArrivedAtBase.cpp
  bt_nodes/IsArrivedAtTarget.cpp
  bt_nodes/IsNoMoreTask.cpp
  bt_nodes/MoveToTarget.cpp
  bt_nodes/ReturnToBase.cpp
  bt_nodes/SetAngle.cpp
  bt_nodes/SkipTarget.cpp
  bt_nodes/TakePhoto.cpp
)
